# Generated by Django 3.0.5 on 2020-06-12 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canadiancommoncv',
            name='_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='date_of_birth',
            field=models.CharField(max_length=5),
        ),
    ]
