# Generated by Django 3.0.5 on 2020-05-02 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='subdivision',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='education',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='ccv.Education'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='organization',
            field=models.OneToOneField(blank=True, help_text='The organization that conferred this credential', null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.Organization'),
        ),
        migrations.AddField(
            model_name='credential',
            name='other_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.OtherOrganization'),
        ),
        migrations.AddField(
            model_name='degree',
            name='organization',
            field=models.OneToOneField(blank=True, help_text='The institution that conferred the degree.', null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.Organization'),
        ),
        migrations.AddField(
            model_name='degree',
            name='other_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.OtherOrganization'),
        ),
        migrations.AddField(
            model_name='identification',
            name='personal_information',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ccv.PersonalInformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicworkexperience',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.Organization'),
        ),
        migrations.AlterField(
            model_name='academicworkexperience',
            name='other_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.OtherOrganization'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='The municipal component (city, town, etc.) of the given address', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='end_date',
            field=models.DateField(blank=True, help_text='If the given address is temporary, the date upon which it becomes inactive', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_1',
            field=models.CharField(blank=True, help_text='The exact location, number and street name for the given address', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_5',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal',
            field=models.CharField(blank=True, help_text='The postal code of the given address', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='start_date',
            field=models.DateField(blank=True, help_text='If the given address is temporary, the date upon which it becomes active', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[('Courier', 'Courier'), ('Home', 'Home'), ('Mailing', 'Mailing'), ('Primary Affiliation', 'Primary Affiliation'), ('Temporary', 'Temporary')], help_text='The nature and intended use of the given address', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='end_date',
            field=models.DateField(blank=True, help_text="The date the person's study was completed", null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='expected_date',
            field=models.DateField(blank=True, help_text="If the person's study is not complete, the date completion is expected", null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(blank=True, help_text="The name of the person's degree program", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='phd_without_masters',
            field=models.BooleanField(blank=True, default=False, help_text='If doctorate degree, did the person transfer directly to this degree without completing a Masters?', null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='specialization',
            field=models.CharField(blank=True, help_text="person's major course of study", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='start_date',
            field=models.DateField(blank=True, help_text="The date the person's study began", null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='status',
            field=models.CharField(blank=True, choices=[('All But Degree', 'All But Degree'), ('Completed', 'Completed'), ('In Progress', 'In Progress'), ('Withdrawn', 'Withdrawn')], help_text="Indicates whether or not the person's degree is completed", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='thesis_title',
            field=models.TextField(blank=True, help_text='itle of the person’s thesis project', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='type',
            field=models.CharField(blank=True, choices=[("Bachelor's", "Bachelor's"), ("Bachelor's Equivalent", "Bachelor's Equivalent"), ("Bachelor's Honours", "Bachelor's Honours"), ("Master's Equivalent", "Master's Equivalent"), ("Master's non-Thesis", "Master's non-Thesis"), ("Master's Thesis", "Master's Thesis"), ('Doctorate', 'Doctorate'), ('Doctorate Equivalent', 'Doctorate Equivalent'), ('Post-doctorate', 'Post-doctorate'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Habilitation', 'Habilitation'), ('Research Associate', 'Research Associate')], help_text="The designation of the person's degree", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='address',
            field=models.CharField(blank=True, help_text="The person's e-mail address", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='end_date',
            field=models.DateField(blank=True, help_text='If the given e-mail is temporary, the date upon which it becomes inactive', null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='start_date',
            field=models.DateField(blank=True, help_text='If the given e-mail is temporary, the date upon which it becomes active', null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(blank=True, choices=[('Personal', 'Personal'), ('Temporary', 'Temporary'), ('Work', 'Work')], help_text='The nature of the given e-mail', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='designated_group',
            field=models.CharField(blank=True, choices=[('Aboriginal', 'Aboriginal'), ('Disabled', 'Disabled'), ('Visible Minority', 'Visible Minority')], help_text='Group designated by the Employment Equity Act of Canada', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='can_read',
            field=models.BooleanField(default=False, help_text='The capacity of the person to comprehend the indicated language in written form.', null=True),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='can_speak',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='can_understand',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='can_write',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='peer_review',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccv.PersonalInformation'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='area_code',
            field=models.CharField(blank=True, help_text='The area code with no space, bracket or dash e.g. 613', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='country_code',
            field=models.CharField(blank=True, help_text='The country code with no space, bracket or dash, if located outside of North America e.g. 011', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='end_date',
            field=models.DateField(blank=True, help_text='If the given number is temporary, the date upon which it becomes inact', null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='extension',
            field=models.CharField(blank=True, help_text='The extension, if applicable, with no space, bracket or dash e.g. 5678', max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='number',
            field=models.CharField(blank=True, help_text='The telephone number with no space, bracket or dash e.g. 1234567', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccv.PersonalInformation'),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('Fax', 'Fax'), ('Home', 'Home'), ('Laboratory', 'Laboratory'), ('Mobile', 'Mobile'), ('Pager', 'Pager'), ('Temporary', 'Temporary'), ('Work', 'Work')], help_text='The nature of the given phone number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='start_date',
            field=models.DateField(blank=True, help_text='If the given number is temporary, the date upon which it becomes active', null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccv.PersonalInformation'),
        ),
        migrations.AlterField(
            model_name='website',
            name='type',
            field=models.CharField(blank=True, choices=[('Blog', 'Blog'), ('Community', 'Community'), ('Corporate', 'Corporate'), ('Personal', 'Personal'), ('Social Media', 'Social Media')], help_text='The nature of the given web address', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.CharField(blank=True, help_text="The person's web address", max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Recognition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, choices=[('Citation', 'Citation'), ('Distinction', 'Distinction'), ('Honor', 'Honor'), ('Prize / Award', 'Prize / Award')], max_length=20, null=True)),
                ('name', models.TextField(blank=True, help_text='The name or title of the recognition', max_length=250, null=True)),
                ('effective_date', models.DateField(blank=True, help_text='The date when the recognition was awarded', null=True)),
                ('end_date', models.DateField(blank=True, help_text='The date when this recognition expires', null=True)),
                ('amount', models.IntegerField(blank=True, help_text='The amount that was awarded for this recognition', null=True)),
                ('amount_in_canadian_dollar', models.IntegerField(blank=True, help_text='Amount in CAN $', null=True)),
                ('currency', models.CharField(blank=True, help_text='The currency in which the money was awarded', max_length=50, null=True)),
                ('organization', models.OneToOneField(blank=True, help_text='The organization that gave the recognition', null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.Organization')),
                ('other_organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.OtherOrganization')),
            ],
            options={
                'db_table': 'recognition',
            },
        ),
        migrations.AddField(
            model_name='areaofresearch',
            name='recognition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.Recognition'),
        ),
        migrations.AddField(
            model_name='fieldofapplication',
            name='recognition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.Recognition'),
        ),
        migrations.AddField(
            model_name='researchdiscipline',
            name='recognition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.Recognition'),
        ),
    ]
