# Generated by Django 3.0.5 on 2020-05-08 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0002_auto_20200502_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identification',
            name='personal_information',
        ),
        migrations.AlterField(
            model_name='academicworkexperience',
            name='position_title',
            field=models.CharField(blank=True, help_text="The person's position at the institution", max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='academicworkexperience',
            name='work_description',
            field=models.CharField(blank=True, help_text='Description of the duties for this position', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccv.Identification'),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='position_title',
            field=models.CharField(blank=True, help_text='The name or title of the position', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='description',
            field=models.CharField(blank=True, help_text='Description of services contributed by the person as part of a committee', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the committee', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='description',
            field=models.CharField(blank=True, help_text="A description of the person's designation", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='title',
            field=models.CharField(blank=True, help_text='The name or title of the designation earned', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='degree',
            name='thesis_title',
            field=models.CharField(blank=True, help_text='title of the person’s thesis project', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccv.Identification'),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccv.Identification'),
        ),
        migrations.AlterField(
            model_name='leavesofabsence',
            name='absence_description',
            field=models.CharField(blank=True, help_text='description of the leave of absence', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='nonacademicworkexperience',
            name='position_title',
            field=models.CharField(blank=True, help_text='The position of the person with the employer', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='othermembership',
            name='description',
            field=models.CharField(blank=True, help_text='Description of services contributed by the person as part of a committee', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='othermembership',
            name='name',
            field=models.CharField(blank=True, help_text='The name of the committee', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='recognition',
            name='name',
            field=models.CharField(blank=True, help_text='The name or title of the recognition', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='researchfundinghistory',
            name='funding_title',
            field=models.CharField(blank=True, help_text='The nature of the grant received', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='researchfundinghistory',
            name='project_description',
            field=models.CharField(blank=True, help_text='description of project for which funding was received', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='researchfundinghistory',
            name='research_uptake',
            field=models.CharField(blank=True, help_text='strategies used to promote the uptake of your research findings.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccv.Identification'),
        ),
        migrations.AlterField(
            model_name='temporalperiod',
            name='from_year',
            field=models.IntegerField(blank=True, help_text='The starting year of the temporal period', null=True),
        ),
        migrations.AlterField(
            model_name='temporalperiod',
            name='to_year',
            field=models.IntegerField(blank=True, help_text='The end year of the temporal period', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='experience_summary',
            field=models.CharField(blank=True, help_text='summary of research experience', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_theory',
            field=models.CharField(blank=True, help_text='The key theories and methodologies used in research', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='research_interest',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='personal_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ccv.Identification'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(blank=True, help_text="The person's web address", max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='academicworkexperience',
            table=None,
        ),
        migrations.AlterModelTable(
            name='activity',
            table=None,
        ),
        migrations.AlterModelTable(
            name='address',
            table=None,
        ),
        migrations.AlterModelTable(
            name='affiliation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='areaofresearch',
            table=None,
        ),
        migrations.AlterModelTable(
            name='countryofcitizenship',
            table=None,
        ),
        migrations.AlterModelTable(
            name='credential',
            table=None,
        ),
        migrations.AlterModelTable(
            name='degree',
            table=None,
        ),
        migrations.AlterModelTable(
            name='disciplinetrainedin',
            table=None,
        ),
        migrations.AlterModelTable(
            name='education',
            table=None,
        ),
        migrations.AlterModelTable(
            name='email',
            table=None,
        ),
        migrations.AlterModelTable(
            name='employment',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fieldofapplication',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fundingbyyear',
            table=None,
        ),
        migrations.AlterModelTable(
            name='fundingsource',
            table=None,
        ),
        migrations.AlterModelTable(
            name='geographicalregion',
            table=None,
        ),
        migrations.AlterModelTable(
            name='identification',
            table=None,
        ),
        migrations.AlterModelTable(
            name='languageskill',
            table=None,
        ),
        migrations.AlterModelTable(
            name='leavesofabsence',
            table=None,
        ),
        migrations.AlterModelTable(
            name='membership',
            table=None,
        ),
        migrations.AlterModelTable(
            name='nonacademicworkexperience',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
        migrations.AlterModelTable(
            name='otherinvestigator',
            table=None,
        ),
        migrations.AlterModelTable(
            name='othermembership',
            table=None,
        ),
        migrations.AlterModelTable(
            name='otherorganization',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recognition',
            table=None,
        ),
        migrations.AlterModelTable(
            name='researchcentre',
            table=None,
        ),
        migrations.AlterModelTable(
            name='researchdiscipline',
            table=None,
        ),
        migrations.AlterModelTable(
            name='researchfundinghistory',
            table=None,
        ),
        migrations.AlterModelTable(
            name='researchsetting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='researchspecializationkeyword',
            table=None,
        ),
        migrations.AlterModelTable(
            name='researchuptakeholder',
            table=None,
        ),
        migrations.AlterModelTable(
            name='supervisor',
            table=None,
        ),
        migrations.AlterModelTable(
            name='technologicalapplication',
            table=None,
        ),
        migrations.AlterModelTable(
            name='telephone',
            table=None,
        ),
        migrations.AlterModelTable(
            name='temporalperiod',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='website',
            table=None,
        ),
        migrations.DeleteModel(
            name='PersonalInformation',
        ),
    ]
