# Generated by Django 3.0.5 on 2020-06-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0002_auto_20200612_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognition',
            name='description',
            field=models.CharField(blank=True, help_text='A description of the recognition obtained', max_length=1000, null=True),
        ),
    ]
