# Generated by Django 3.0.5 on 2020-06-14 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0003_recognition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognition',
            name='ccv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccv.CanadianCommonCv'),
        ),
    ]
