# Generated by Django 3.0.5 on 2020-06-14 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0004_auto_20200614_0539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='researchspecializationkeyword',
            name='order',
            field=models.IntegerField(blank=True, help_text='This field is used to order the entries. A value of 1 will show up at top.', null=True),
        ),
        migrations.AlterField(
            model_name='canadiancommoncv',
            name='_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
