# Generated by Django 3.0.5 on 2020-06-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0006_auto_20200614_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaofresearch',
            name='order',
            field=models.IntegerField(blank=True, help_text='This field is used to order the entries. A value of 1 will show up at top.', null=True),
        ),
        migrations.AddField(
            model_name='fieldofapplication',
            name='order',
            field=models.IntegerField(blank=True, help_text='This field is used to order the entries. A value of 1 will show up at top.', null=True),
        ),
        migrations.AddField(
            model_name='researchdiscipline',
            name='order',
            field=models.IntegerField(blank=True, help_text='This field is used to order the entries. A value of 1 will show up at top.', null=True),
        ),
    ]
