# Generated by Django 3.0.5 on 2020-06-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0007_auto_20200614_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaofresearch',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
