# Generated by Django 3.0.7 on 2020-06-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0008_auto_20200614_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='MostSignificantContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='A title, name, or short description of the contribution', max_length=250, null=True)),
                ('contribution_date', models.DateField(blank=True, help_text='The key date associated with this contribution (e.g. publication date, activity start date, etc.)', null=True)),
                ('description', models.CharField(blank=True, help_text='Provide a concise description of this contribution, its value to the area of research fr which u are applying for funding & potential impact', max_length=1000, null=True)),
                ('ccv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ccv.CanadianCommonCv')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
