# Generated by Django 3.0.7 on 2020-06-23 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0010_auto_20200622_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonacademicworkexperience',
            name='other_organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ccv.OtherOrganization'),
        ),
    ]
