# Generated by Django 3.0.7 on 2020-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0012_auto_20200623_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='organization',
            field=models.CharField(blank=True, help_text='Organization that provided funding for this project', max_length=100, null=True),
        ),
    ]
