# Generated by Django 3.0.7 on 2020-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0013_auto_20200623_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicworkexperience',
            name='department',
            field=models.CharField(blank=True, help_text='The department within the given institution', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, help_text='The municipal component (city, town, etc.) of the given address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_1',
            field=models.CharField(blank=True, help_text='The exact location, number and street name for the given address', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='line_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='areaofresearch',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='areaofresearch',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='areaofresearch',
            name='subfield',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artisticexhibition',
            name='venue',
            field=models.CharField(blank=True, help_text='The venue where it was presented', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='distributor',
            field=models.CharField(blank=True, help_text='The name of the distributor of the album', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='producer',
            field=models.CharField(blank=True, help_text="The producer's name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_city',
            field=models.CharField(blank=True, help_text='City where the publication was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='publication_city',
            field=models.CharField(blank=True, help_text='City where the publication was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='network_name',
            field=models.CharField(blank=True, help_text='The network on which the program was broadcasted', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clinicalcareguideline',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='codeveloper',
            name='family_name',
            field=models.CharField(blank=True, help_text='Family name of person who participated in the development of the course', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='codeveloper',
            name='first_name',
            field=models.CharField(blank=True, help_text='First name of person who participated in the development of the course', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coinstructor',
            name='family_name',
            field=models.CharField(blank=True, help_text='The family name of the instructor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coinstructor',
            name='first_name',
            field=models.CharField(blank=True, help_text='The first name of the instructor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='conferencepublication',
            name='conference_location',
            field=models.CharField(blank=True, help_text='The country where the conference was held.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contributionfundingsource',
            name='organisation',
            field=models.CharField(blank=True, help_text='Main funding org name who has funded this contribution', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contributionfundingsource',
            name='other_organization',
            field=models.CharField(blank=True, help_text='If someone cannot find the org from the list', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='countryofcitizenship',
            name='name',
            field=models.CharField(blank=True, help_text='List all countries that the person is a citizen of', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='location',
            field=models.CharField(blank=True, help_text='The country of the publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encyclopediaentry',
            name='publication_city',
            field=models.CharField(blank=True, help_text='City where the publication was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitioncatalogue',
            name='gallery_publisher',
            field=models.CharField(blank=True, help_text='The name of the gallery or publisher for which the catalogue was created', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitioncatalogue',
            name='publication_location',
            field=models.CharField(blank=True, help_text='The place where the catalogue was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldofapplication',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fieldofapplication',
            name='subfield',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='other_organization',
            field=models.CharField(blank=True, help_text="The funding organization's name, only if not in the above column", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='program_name',
            field=models.CharField(blank=True, help_text="The funding organization's name, only if not in the above list", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='canadian_residency_status',
            field=models.CharField(blank=True, choices=[('Canadian Citizen', 'Canadian Citizen'), ('Not Applicable', 'Not Applicable'), ('Permanent Resident', 'Permanent Resident'), ('Refugee', 'Refugee'), ('Student Work Permit', 'Student Work Permit'), ('Study Permit', 'Study Permit'), ('Visitor Visa', 'Visitor Visa'), ('Work Permit', 'Work Permit')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='designated_group',
            field=models.CharField(blank=True, choices=[('Aboriginal', 'Aboriginal'), ('Disabled', 'Disabled'), ('Visible Minority', 'Visible Minority')], help_text='Group designated by the Employment Equity Act of Canada', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='family_name',
            field=models.CharField(help_text="A person's surname", max_length=100),
        ),
        migrations.AlterField(
            model_name='identification',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='identification',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='permanent_residency',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='previous_family_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='previous_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='identification',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Professor', 'Professor'), ('Reverend', 'Reverend')], max_length=100),
        ),
        migrations.AlterField(
            model_name='internationalcollaborationactivity',
            name='role',
            field=models.CharField(blank=True, help_text='The role of the person in this activity', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publication_location',
            field=models.CharField(blank=True, help_text='The country where it was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manual',
            name='publication_city',
            field=models.CharField(blank=True, help_text='City where the publication was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='museumexhibition',
            name='venue',
            field=models.CharField(blank=True, help_text='The venue in which the exhibition was given', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musicalcompilation',
            name='publication_location',
            field=models.CharField(blank=True, help_text='The place where the composition was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musicalcompilation',
            name='publisher',
            field=models.CharField(blank=True, help_text='The publisher of the composition', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='musicalperformance',
            name='venue',
            field=models.CharField(blank=True, help_text='The venue where it was presented', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='othermembership',
            name='role',
            field=models.CharField(blank=True, help_text="The person's role in this activity", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otherorganization',
            name='name',
            field=models.CharField(blank=True, help_text="The organization's name, only if not in Organization list", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='location',
            field=models.CharField(blank=True, help_text='The country in which the patent resides', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patent',
            name='number',
            field=models.CharField(blank=True, help_text='The number of the patent', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='performanceart',
            name='venue',
            field=models.CharField(blank=True, help_text='The venue in which the performance was given', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='appeared_in',
            field=models.CharField(blank=True, help_text='The name of the publication in which the work appeared, if applicable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='issue',
            field=models.CharField(blank=True, help_text='The issue, if applicable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='page_range',
            field=models.CharField(blank=True, help_text="The page range with a dash ('-') as separator (e.g. 234-256), if applicable", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='publisher',
            field=models.CharField(blank=True, help_text='The name of the publisher, if applicable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='volume',
            field=models.CharField(blank=True, help_text='The volume, if applicable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='city',
            field=models.CharField(blank=True, help_text='The city where the conference took place', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='location',
            field=models.CharField(blank=True, help_text='The country where the conference took place', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='url',
            field=models.URLField(blank=True, help_text='The name of an associated website, if applicable', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicationstaticabstract',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publicationstaticabstract',
            name='publication_location',
            field=models.CharField(blank=True, help_text='The place where it was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='radioandtvprogram',
            name='publication_location',
            field=models.CharField(blank=True, help_text='The place where the composition was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchcentre',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchcentre',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchcentre',
            name='subdivision',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchdiscipline',
            name='discipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchdiscipline',
            name='field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='researchdiscipline',
            name='sector_of_discipline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setdesign',
            name='venue',
            field=models.CharField(blank=True, help_text='The venue in which the exhibition was given', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sounddesign',
            name='venue',
            field=models.CharField(blank=True, help_text='The venue in which the exhibition was given', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentcountryofcitizenship',
            name='country_name',
            field=models.CharField(blank=True, help_text='Country of citizenship of the student', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecognition',
            name='organisation',
            field=models.CharField(blank=True, help_text='The organization that gave the recognition', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecognition',
            name='other_organization',
            field=models.CharField(blank=True, help_text='If someone cannot find the org from the list', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technologicalapplication',
            name='category',
            field=models.CharField(blank=True, choices=[('Agro-alimentary', 'Agro-alimentary'), ('Chemistry / Biochemistry', 'Chemistry / Biochemistry'), ('Medical materials and instrumentation', 'Medical materials and instrumentation'), ('Orthopaedic devices', 'Orthopaedic devices'), ('Pharmacy', 'Pharmacy')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technologicalapplication',
            name='subfield',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telephone',
            name='phone_type',
            field=models.CharField(blank=True, choices=[('Fax', 'Fax'), ('Home', 'Home'), ('Laboratory', 'Laboratory'), ('Mobile', 'Mobile'), ('Pager', 'Pager'), ('Temporary', 'Temporary'), ('Work', 'Work')], help_text='The nature of the given phone number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='theatreperformanceandproduction',
            name='venue',
            field=models.CharField(blank=True, help_text='The venue in which the exhibition was given', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thesisdissertation',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='publication_city',
            field=models.CharField(blank=True, help_text='City where the publication was published', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workingpaper',
            name='doi',
            field=models.CharField(blank=True, help_text='digital object identifier (DOI) for this publication', max_length=100, null=True),
        ),
    ]
