# Generated by Django 3.0.7 on 2020-06-23 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0014_auto_20200623_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionfundingsource',
            name='presentation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ccv.Presentation'),
            preserve_default=False,
        ),
    ]
