# Generated by Django 3.0.7 on 2020-06-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0015_contributionfundingsource_presentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionfundingsource',
            name='presentation',
        ),
        migrations.AlterField(
            model_name='artisticexhibition',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_artisticexhibition_related', related_query_name='ccv_artisticexhibitions', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='audiorecording',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_audiorecording_related', related_query_name='ccv_audiorecordings', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_bookreview_related', related_query_name='ccv_bookreviews', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='broadcastinterview',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_broadcastinterview_related', related_query_name='ccv_broadcastinterviews', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='choreography',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_choreography_related', related_query_name='ccv_choreographys', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='clinicalcareguideline',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_clinicalcareguideline_related', related_query_name='ccv_clinicalcareguidelines', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_dictionaryentry_related', related_query_name='ccv_dictionaryentrys', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='disclosure',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_disclosure_related', related_query_name='ccv_disclosures', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='exhibitioncatalogue',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_exhibitioncatalogue_related', related_query_name='ccv_exhibitioncatalogues', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='fiction',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_fiction_related', related_query_name='ccv_fictions', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_journal_related', related_query_name='ccv_journals', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='license',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_license_related', related_query_name='ccv_licenses', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='lightdesign',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_lightdesign_related', related_query_name='ccv_lightdesigns', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_litigation_related', related_query_name='ccv_litigations', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='museumexhibition',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_museumexhibition_related', related_query_name='ccv_museumexhibitions', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='musicalcompilation',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_musicalcompilation_related', related_query_name='ccv_musicalcompilations', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='musicalperformance',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_musicalperformance_related', related_query_name='ccv_musicalperformances', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='otherartisticcontribution',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_otherartisticcontribution_related', related_query_name='ccv_otherartisticcontributions', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_patent_related', related_query_name='ccv_patents', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='performanceart',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_performanceart_related', related_query_name='ccv_performancearts', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='poetry',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_poetry_related', related_query_name='ccv_poetrys', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_presentation_related', related_query_name='ccv_presentations', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='publicationstaticabstract',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_publicationstaticabstract_related', related_query_name='ccv_publicationstaticabstracts', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='radioandtvprogram',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_radioandtvprogram_related', related_query_name='ccv_radioandtvprograms', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='registeredcopyright',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_registeredcopyright_related', related_query_name='ccv_registeredcopyrights', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='report',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_report_related', related_query_name='ccv_reports', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='scripts',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_scripts_related', related_query_name='ccv_scriptss', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='setdesign',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_setdesign_related', related_query_name='ccv_setdesigns', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='sounddesign',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_sounddesign_related', related_query_name='ccv_sounddesigns', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='test',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_test_related', related_query_name='ccv_tests', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='textinterview',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_textinterview_related', related_query_name='ccv_textinterviews', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='theatreperformanceandproduction',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_theatreperformanceandproduction_related', related_query_name='ccv_theatreperformanceandproductions', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='thesisdissertation',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_thesisdissertation_related', related_query_name='ccv_thesisdissertations', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_trademark_related', related_query_name='ccv_trademarks', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='videorecording',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_videorecording_related', related_query_name='ccv_videorecordings', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='visualartwork',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_visualartwork_related', related_query_name='ccv_visualartworks', to='ccv.ContributionFundingSource'),
        ),
        migrations.AlterField(
            model_name='workingpaper',
            name='funding_source',
            field=models.ManyToManyField(related_name='ccv_workingpaper_related', related_query_name='ccv_workingpapers', to='ccv.ContributionFundingSource'),
        ),
    ]
