# Generated by Django 3.0.7 on 2020-06-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0016_auto_20200623_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='publishing_status',
            field=models.CharField(blank=True, choices=[('Accepted', 'Accepted'), ('In Press', 'In Press'), ('Published', 'Published'), ('Revision Requested', 'Revision Requested'), ('Submitted', 'Submitted')], help_text='The status of the article with regard to journal', max_length=30, null=True),
        ),
    ]
