# Generated by Django 3.0.7 on 2020-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0017_journal_publishing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioandtvprogram',
            name='publisher',
            field=models.CharField(blank=True, help_text='The publisher of the composition', max_length=100, null=True),
        ),
    ]
