# Generated by Django 3.0.7 on 2020-06-25 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0018_radioandtvprogram_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='setdesign',
            name='artistic_contribution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ccv.ArtisticContribution'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sounddesign',
            name='artistic_contribution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ccv.ArtisticContribution'),
            preserve_default=False,
        ),
    ]
