# Generated by Django 3.0.7 on 2020-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0020_auto_20200625_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
