# Generated by Django 3.0.7 on 2020-07-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccv', '0022_auto_20200629_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='is_refereed',
            field=models.NullBooleanField(help_text='Indicate if the project was refereed'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='is_refereed',
            field=models.NullBooleanField(help_text='Indicate if the project was refereed'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='is_refereed',
            field=models.NullBooleanField(help_text='Indicate if the project was refereed'),
        ),
        migrations.AlterField(
            model_name='conferencepublication',
            name='is_invited',
            field=models.NullBooleanField(help_text='Indicate whether  author was invited to present at the conference'),
        ),
        migrations.AlterField(
            model_name='conferencepublication',
            name='is_refereed',
            field=models.NullBooleanField(help_text='Indicate whether the document was refereed'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_open_access',
            field=models.NullBooleanField(help_text='Indicate if the journal is open access'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_refereed',
            field=models.NullBooleanField(help_text='Indicate if the journal is refereed'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='is_synthesis',
            field=models.NullBooleanField(help_text='contextualization and integration of research findings of individual research within the larger body of knowledge on topic'),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='peer_review',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='is_competitive',
            field=models.NullBooleanField(help_text='Indicate if participation in this event was competitive'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='is_invited',
            field=models.NullBooleanField(help_text='Indicate whether the person was invited to present the information'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='is_keynote',
            field=models.NullBooleanField(help_text='Indicate whether the person gave the keynote address at this event'),
        ),
        migrations.AlterField(
            model_name='report',
            name='is_synthesis',
            field=models.NullBooleanField(help_text='contextualization and integration of research findings of individual research studies within the larger body of knowledge on he topic'),
        ),
    ]
